table:
  name: reviewdata
  schema: public
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - name
      filter: {}
      allow_aggregations: true
      query_root_fields:
        - select_aggregate
        - select
        - select_by_pk
      subscription_root_fields:
        - select_aggregate
        - select
        - select_by_pk
event_triggers:
  - name: blogdata
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: http://localhost:8080/blogdata
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
